CREATE TABLE EZ_USUARIO(
	ID SERIAL PRIMARY KEY NOT NULL,
    USUARIO TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    SENHA TEXT NOT NULL,
    NUMERO_CELULAR TEXT NOT NULL,
    IS_ATIVO CHAR(1) NOT NULL,
    CHECK (IS_ATIVO = 'S' OR IS_ATIVO = 'N')
);

CREATE TABLE EZ_PACIENTE(
	ID SERIAL PRIMARY KEY NOT NULL,
    ID_USUARIO INTEGER REFERENCES EZ_USUARIO (ID),
    NOME TEXT,
    DATA_NASCIMENTO DATE,
    PESO FLOAT(2),
    ALTURA FLOAT(2)
);

CREATE TABLE EZ_ENDERECO(
    ID SERIAL PRIMARY KEY NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CIDADE TEXT NOT NULL,
    CEP TEXT NOT NULL,
    BAIRRO TEXT NOT NULL,
    RUA TEXT NOT NULL,
    NUMERO INTEGER NOT NULL,
    COMPLEMENTO TEXT
);

CREATE TABLE EZ_FARMACIA(
	ID SERIAL PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    ID_ENDERECO INTEGER NOT NULL REFERENCES EZ_ENDERECO (ID)
);

CREATE TABLE EZ_FARMACIA_FAV(
	ID SERIAL PRIMARY KEY NOT NULL,
	ID_PACIENTE INTEGER REFERENCES EZ_PACIENTE (ID),
	ID_FARMACIA INTEGER REFERENCES EZ_FARMACIA (ID)
);

CREATE TABLE EZ_TIPO_MEDICAMENTO(
	ID SERIAL PRIMARY KEY NOT NULL,
    TIPO TEXT NOT NULL
);

CREATE TABLE EZ_MEDICAMENTO(
	ID SERIAL PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    ID_TIPO_MEDICAMENTO INTEGER REFERENCES EZ_TIPO_MEDICAMENTO (ID)
);

CREATE TABLE EZ_ESTOQUE(
	ID SERIAL PRIMARY KEY NOT NULL,
    ID_MEDICAMENTO INTEGER REFERENCES EZ_MEDICAMENTO(ID),
    QUANTIDADE INTEGER NOT NULL
);

CREATE TABLE EZ_ESTOQUE_PACIENTE(
	ID SERIAL PRIMARY KEY NOT NULL,
	ID_PACIENTE INTEGER REFERENCES EZ_PACIENTE (ID),
	ID_ESTOQUE INTEGER REFERENCES EZ_ESTOQUE (ID)
);

CREATE TABLE EZ_TIPO_DOSE(
	ID SERIAL PRIMARY KEY NOT NULL,
    TIPO TEXT NOT NULL
);

CREATE TABLE EZ_TRATAMENTO(
	ID SERIAL PRIMARY KEY NOT NULL,
	ID_PACIENTE INTEGER REFERENCES EZ_PACIENTE(ID),
    ID_MEDICAMENTO INTEGER REFERENCES EZ_MEDICAMENTO(ID),
    QUANTIDADE_DOSE INTEGER,
    TIPO_DOSE INTEGER REFERENCES EZ_TIPO_DOSE(ID),
    INICIO DATE NOT NULL,
    FIM DATE NOT NULL,
    OBSERVACAO TEXT NOT NULL
);

CREATE TABLE EZ_SEMANA(
    ID SERIAL PRIMARY KEY NOT NULL,
    DIA TEXT NOT NULL
);

CREATE TABLE EZ_ALERTA(
	ID SERIAL PRIMARY KEY NOT NULL,
    ID_TRATAMENTO INTEGER REFERENCES EZ_TRATAMENTO(ID),
    HORARIO TIME NOT NULL,
    DIA_SEMANA INTEGER REFERENCES EZ_SEMANA(ID),
    IS_ATIVO CHAR(1) NOT NULL,
    CHECK (IS_ATIVO = 'S' OR IS_ATIVO = 'N')
);

CREATE TABLE EZ_CUIDADOR(
    ID SERIAL PRIMARY KEY NOT NULL,
	ID_PACIENTE INTEGER REFERENCES EZ_PACIENTE(ID),
    NOME TEXT,
    NUMERO_CELULAR TEXT,
    EMAIL TEXT,
    OBSERVACAO TEXT
);